a = float (input ("Podaj pierwszą liczbę "))
b = float (input ("Podaj drugą liczbę "))
print("Suma:", a+b)
print("Różnica:", a-b)
print("Iloczyn:", a*b)
print("Iloraz:", a/b)
print("Reszta z dzielenia:", a%b)